<?php

/**
 * Implementation of hook_init().
 */
function commerce_buy_one_click_phone_init() {
  if (!path_is_admin(current_path())) {
    drupal_add_js(libraries_get_path('maskedinput') . '/jquery.maskedinput-1.3.js');
    drupal_add_js(drupal_get_path('module', 'commerce_buy_one_click_phone') . '/commerce_buy_one_click_phone.js');
  }
}

/**
 * Implementation of hook_commerce_buy_one_click_form_alter().
 */
function commerce_buy_one_click_phone_commerce_buy_one_click_form_alter(&$form) {
  $form['form_wrapper']['commerce_buy_one_click_phone'] = array(
    '#title' => t('Your phone'),
    '#type' => 'textfield',
    '#default_value' => '',
    '#weight' => 15,
    '#required' => TRUE,
  );
}

/**
 * Implementation of hook_commerce_buy_one_click_admin_email_data_alter().
 */
function commerce_buy_one_click_phone_commerce_buy_one_click_admin_email_data_alter(&$admin_email_data, $form, $form_state) {
  $admin_email_data['commerce_buy_one_click']['commerce-buy-one-click-phone'] = trim($form_state['values']['commerce_buy_one_click_phone']);
}

/**
 * Implementation of hook_commerce_buy_one_click_form_validate_alter().
 */
function commerce_buy_one_click_phone_commerce_buy_one_click_form_validate_alter(&$errors, $form, $form_state) {
  if (empty($form_state['values']['commerce_buy_one_click_phone'])) {
    $errors = t('Error: phone must be specified.');
  }
}

/**
 * Implementation of hook_commerce_buy_one_click_form_submit_alter().
 */
function commerce_buy_one_click_phone_commerce_buy_one_click_form_submit_alter($order, $order_user, $form, $form_state) {
  $phone = trim($form_state['values']['commerce_buy_one_click_phone']);
  $name = t('Buy one click');
  if (!empty($form_state['values']['commerce_buy_one_click_name'])) {
    $name = $form_state['values']['commerce_buy_one_click_name'];
  }
  if (!empty($phone) || !empty($name)) {
    $phone = trim($phone);
    
    // Update billing profile with user data.
    if (empty($order->commerce_customer_billing)) {
      $profile = commerce_customer_profile_new('billing', $order_user->uid);
      _commerce_buy_one_click_phone_update_billing_profile($profile, $phone, $name);
      $profile_object = array(
        'und' => array(
          array(
            'profile_id' => $profile->profile_id,
          ),
        ),
      );
      $order->commerce_customer_billing = $profile_object;
      commerce_order_save($order);
    }
    else {
      $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
      $profile = commerce_customer_profile_load($order_wrapper->commerce_customer_billing->profile_id->value());
      _commerce_buy_one_click_phone_update_billing_profile($profile, $phone, $name);
    }
  }
}

/**
 * Update billing profile function.
 */
function _commerce_buy_one_click_phone_update_billing_profile(&$profile, $phone, $name) {
  $profile_wrapper = entity_metadata_wrapper('commerce_customer_profile', $profile);
  $profile_wrapper->field_phone = $phone;
  $profile_wrapper->field_name = $name;
  commerce_customer_profile_save($profile);
}
